# Generated by Django 2.2.3 on 2019-10-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lane_count', models.PositiveSmallIntegerField(default=None, null=True)),
                ('barricade', models.BooleanField(default=False)),
                ('shut_reason', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roads.Road')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('destination_latitude', models.BigIntegerField()),
                ('destination_longitude', models.BigIntegerField()),
                ('authority', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roads.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('aqi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ldr', models.IntegerField()),
                ('hits', models.PositiveSmallIntegerField()),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roads.Road')),
            ],
        ),
    ]
