# Generated by Django 2.2.3 on 2019-10-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_auto_20191012_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyvehicle',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roads.Authority'),
        ),
    ]
